--- !ruby/object:Jumpstart::Configuration
application_name: Integrator
business_name: Integrator Company, LLC
domain: example.com
support_email: omater@msn.com
default_from_email: Jumpstart <support@example.com>
business_address: ''
background_job_processor: async
email_provider: ''
personal_accounts: true
solargraph: false
register_with_account: true
apns: false
fcm: false
collect_billing_address: false
